/// List taken from <https://www.w3.org/TR/SVG11/types.html#ColorKeywords>
pub static COLOUR_LIST: &[&str] = &[
    "aliceblue",
    "antiquewhite",
    "aqua",
    "aquamarine",
    "azure",
    "beige",
    "bisque",
    "black",
    "blanchedalmond",
    "blue",
    "blueviolet",
    "brown",
    "burlywood",
    "cadetblue",
    "chartreuse",
    "chocolate",
    "coral",
    "cornflowerblue",
    "cornsilk",
    "crimson",
    "cyan",
    "darkblue",
    "darkcyan",
    "darkgoldenrod",
    "darkgray",
    "darkgreen",
    "darkgrey",
    "darkkhaki",
    "darkmagenta",
    "darkolivegreen",
    "darkorange",
    "darkorchid",
    "darkred",
    "darksalmon",
    "darkseagreen",
    "darkslateblue",
    "darkslategray",
    "darkslategrey",
    "darkturquoise",
    "darkviolet",
    "deeppink",
    "deepskyblue",
    "dimgray",
    "dimgrey",
    "dodgerblue",
    "firebrick",
    "floralwhite",
    "forestgreen",
    "fuchsia",
    "gainsboro",
    "ghostwhite",
    "gold",
    "goldenrod",
    "gray",
    "green",
    "greenyellow",
    "grey",
    "honeydew",
    "hotpink",
    "indianred",
    "indigo",
    "ivory",
    "khaki",
    "lavender",
    "lavenderblush",
    "lawngreen",
    "lemonchiffon",
    "lightblue",
    "lightcoral",
    "lightcyan",
    "lightgoldenrodyellow",
    "lightgray",
    "lightgreen",
    "lightgrey",
    "lightpink",
    "lightsalmon",
    "lightseagreen",
    "lightskyblue",
    "lightslategray",
    "lightslategrey",
    "lightsteelblue",
    "lightyellow",
    "lime",
    "limegreen",
    "linen",
    "magenta",
    "maroon",
    "mediumaquamarine",
    "mediumblue",
    "mediumorchid",
    "mediumpurple",
    "mediumseagreen",
    "mediumslateblue",
    "mediumspringgreen",
    "mediumturquoise",
    "mediumvioletred",
    "midnightblue",
    "mintcream",
    "mistyrose",
    "moccasin",
    "navajowhite",
    "navy",
    // Also include 'none' which is a valid stroke & fill value
    "none",
    "oldlace",
    "olive",
    "olivedrab",
    "orange",
    "orangered",
    "orchid",
    "palegoldenrod",
    "palegreen",
    "paleturquoise",
    "palevioletred",
    "papayawhip",
    "peachpuff",
    "peru",
    "pink",
    "plum",
    "powderblue",
    "purple",
    "red",
    "rosybrown",
    "royalblue",
    "saddlebrown",
    "salmon",
    "sandybrown",
    "seagreen",
    "seashell",
    "sienna",
    "silver",
    "skyblue",
    "slateblue",
    "slategray",
    "slategrey",
    "snow",
    "springgreen",
    "steelblue",
    "tan",
    "teal",
    "thistle",
    "tomato",
    "turquoise",
    "violet",
    "wheat",
    "white",
    "whitesmoke",
    "yellow",
    "yellowgreen",
];

/// The following - a subset of `COLOUR_LIST` - are (subjectively) 'dark'
/// and by default will have white text rather than black when used as a
/// fill style (e.g. `d-fill-brown`)
pub static DARK_COLOURS: &[&str] = &[
    "black",
    "blue",
    "blueviolet",
    "brown",
    "cadetblue",
    "chocolate",
    "coral",
    "cornflowerblue",
    "crimson",
    "darkblue",
    "darkcyan",
    "darkgoldenrod",
    "darkgray",
    "darkgreen",
    "darkgrey",
    "darkkhaki",
    "darkmagenta",
    "darkolivegreen",
    "darkorange",
    "darkorchid",
    "darkred",
    "darksalmon",
    "darkseagreen",
    "darkslateblue",
    "darkslategray",
    "darkslategrey",
    "darkturquoise",
    "darkviolet",
    "deeppink",
    "deepskyblue",
    "dimgray",
    "dimgrey",
    "dodgerblue",
    "firebrick",
    "forestgreen",
    "fuchsia",
    "goldenrod",
    "gray",
    "green",
    "grey",
    "hotpink",
    "indianred",
    "indigo",
    "lightcoral",
    "lightslategray",
    "lightslategrey",
    "magenta",
    "maroon",
    "mediumaquamarine",
    "mediumblue",
    "mediumorchid",
    "mediumpurple",
    "mediumseagreen",
    "mediumslateblue",
    "mediumturquoise",
    "mediumvioletred",
    "midnightblue",
    "navy",
    "olive",
    "olivedrab",
    "orange",
    "orangered",
    "orchid",
    "palevioletred",
    "purple",
    "red",
    "rosybrown",
    "royalblue",
    "saddlebrown",
    "seagreen",
    "sienna",
    "slateblue",
    "slategray",
    "slategrey",
    "steelblue",
    "teal",
    "tomato",
];

#[cfg(test)]
mod tests {
    use super::*;

    /// Test that the COLOUR_LIST and DARK_COLOURS are sorted, allowing
    /// binary search to be used.

    #[test]
    fn test_colour_list_sorted() {
        // Ensure COLOUR_LIST is sorted for binary search
        let mut sorted = COLOUR_LIST.to_vec();
        sorted.sort();
        assert_eq!(COLOUR_LIST, sorted);
    }

    #[test]
    fn test_dark_colours_sorted() {
        // Ensure DARK_COLOURS is sorted for binary search
        let mut sorted = DARK_COLOURS.to_vec();
        sorted.sort();
        assert_eq!(DARK_COLOURS, sorted);
    }

    #[test]
    fn test_colour_binsearch() {
        // Test binary search on COLOUR_LIST
        let colour = "darkblue";
        let index = COLOUR_LIST.binary_search(&colour);
        assert!(index.is_ok());
        assert_eq!(COLOUR_LIST[index.unwrap()], colour);

        // Test binary search on DARK_COLOURS
        let dark_colour = "darkred";
        let dark_index = DARK_COLOURS.binary_search(&dark_colour);
        assert!(dark_index.is_ok());
        assert_eq!(DARK_COLOURS[dark_index.unwrap()], dark_colour);
    }
}
